name: Publish Docker image

permissions:
  packages: write
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: ["main"]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-agixt:
    uses: localagi/AI-pipeline/.github/workflows/operation-docker-build-publish.yml@v4
    with:
      registry-dockerhub-enable: ${{ github.event_name != 'pull_request' }}
      registry-repo-name: AGiXT
      registry-readme: ./docs/README.md
      tags: |
        type=schedule
        type=ref,event=branch
        type=semver,pattern={{version}}
      platforms: linux/amd64,linux/arm64/v8
      build-args: BUILDKIT_INLINE_CACHE=1
      cache-from: type=registry,ref=joshxt/agixt:main
      cache-to: type=registry,ref=joshxt/agixt:main,mode=max
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  test-agixt:
    uses: localagi/AI-pipeline/.github/workflows/operation-test-with-jupyter.yml@v4
    with:
      notebook: tests/quickchecks.ipynb
      image: ${{ needs.build-agixt.outputs.primary-image }}
      port: "7437" 
      additional-python-dependencies: requests
    needs: build-agixt
